name: build-spm

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: macos-latest
    outputs:
      VERSION: ${{ steps.vars.outputs.VERSION }}
      CHECKSUM: ${{ steps.xcf.outputs.CHECKSUM }}
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Restore the cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-build

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2

      - name: Set version
        id: vars
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Create XCFramework
        id: xcf
        run: |
          ./gradlew assembleUMDReleaseXCFramework
          cd library/build/XCFrameworks/release
          zip -r -9 $GITHUB_WORKSPACE/umd-xcframework.zip .
          CHECKSUM=$(swift package compute-checksum $GITHUB_WORKSPACE/umd-xcframework.zip)
          echo "CHECKSUM=$CHECKSUM" >> $GITHUB_OUTPUT

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: ./umd-xcframework.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      # The `fetch-depth: 0` is important to fetch all the tags
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch artifact
        uses: actions/download-artifact@v4
        with:
          name: binaries

      - name: Update templates
        run: |
          sed -e 's/{{ version }}/${{ needs.build.outputs.VERSION }}/g' \
            -e 's/{{ checksum }}/${{ needs.build.outputs.CHECKSUM }}/g' \
            template/Package.swift.tpl > Package.swift

          sed -e 's/{{ version }}/${{ needs.build.outputs.VERSION }}/g' \
            template/README.md.tpl > README.md

      - name: Creating the changelog
        run: |
          echo "Changes in this release:" > changelog.md
          git log $(git describe --tags --abbrev=0 \
          $(git rev-list --tags --skip=1 --max-count=1))..HEAD --oneline \
          --pretty=format:"- %s" >> changelog.md
          echo -e "\n---" >> changelog.md
          echo "**XCFramework Checksum**: ${{ needs.build.outputs.CHECKSUM }}" >> changelog.md

      - name: Temporarily delete the tag
        run: |
          git config --global user.name 'vegidio'
          git config --global user.email 'me@vinicius.io'
          git tag -d ${{ needs.build.outputs.VERSION }}
          git push origin :refs/tags/${{ needs.build.outputs.VERSION }}

      - name: Committing changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 🔖 Bumped version to ${{ needs.build.outputs.VERSION }}
          branch: main
          tagging_message: ${{ needs.build.outputs.VERSION }}
          file_pattern: "Package.swift README.md"
          commit_author: Vinicius Egidio <me@vinicius.io>

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ needs.build.outputs.VERSION }}
          tag: ${{ needs.build.outputs.VERSION }}
          bodyFile: changelog.md
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "*.zip"
